name: Daily bot run

on:

  schedule:
    - cron: '40 12 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
      - name: Run npm install
        run: npm i
      - name: Run npm start
        run: npm start
        env: 
          TOKEN: ${{ secrets.TOKEN_DEV }}
          SENDING_TIME: ${{ secrets.SENDING_TIME_DEV }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID_DEV }}
          ROLE_ID: ${{ secrets.ROLE_ID_DEV }}
